name: carpi-course-planner-deployment

services:
  # --- NGINX ---
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - api
      - sis_scraper
      - web

  # --- Database ---
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${DB_USERNAME}",
          "--password=${DB_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  # --- API (Fetched from GHCR) ---
  api:
    image: ghcr.io/project-carpi/api:latest
    restart: always
    environment:
      DB_DIALECT: ${DB_DIALECT}
      DB_API: ${DB_API}
      # Hardcode the DB_HOSTNAME environment variable
      DB_HOSTNAME: db:3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
    depends_on:
      db:
        condition: service_healthy

  # --- SIS Scraper (Fetched from GHCR) ---
  sis_scraper:
    image: ghcr.io/project-carpi/sis-scraper:latest
    restart: always
    environment:
      SCRAPER_LOGS_DIR: ${SCRAPER_LOGS_DIR}
      SCRAPER_CODE_MAPS_DIR: ${SCRAPER_CODE_MAPS_DIR}
      SCRAPER_RAW_OUTPUT_DATA_DIR: ${SCRAPER_RAW_OUTPUT_DATA_DIR}
      SCRAPER_PROCESSED_OUTPUT_DATA_DIR: ${SCRAPER_PROCESSED_OUTPUT_DATA_DIR}
      ATTRIBUTE_CODE_NAME_MAP_FILENAME: ${ATTRIBUTE_CODE_NAME_MAP_FILENAME}
      INSTRUCTOR_RCSID_NAME_MAP_FILENAME: ${INSTRUCTOR_RCSID_NAME_MAP_FILENAME}
      RESTRICTION_CODE_NAME_MAP_FILENAME: ${RESTRICTION_CODE_NAME_MAP_FILENAME}
      SUBJECT_CODE_NAME_MAP_FILENAME: ${SUBJECT_CODE_NAME_MAP_FILENAME}
      DB_DIALECT: ${DB_DIALECT}
      DB_API: ${DB_API}
      # Hardcode the DB_HOSTNAME environment variable
      DB_HOSTNAME: db:3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
    depends_on:
      db:
        condition: service_healthy

  # --- Web App (Fetched from GHCR) ---
  web:
    image: ghcr.io/project-carpi/site:latest
    restart: always

volumes:
  mysql_data:
